In [18]:
import MetaTrader5 as mt5
import json

In [19]:
with open('C:\\Users\\rodri\\OneDrive\\Área de Trabalho\\credentials.json') as f:
   data = json.load(f)

# Conectar com MetaTrader5
if not mt5.initialize(login=data['loginJson'], password=data['passwordJson'], server=data['serverJson']):
    print("initialize() failed, error code = ", mt5.last_error())
    mt5.shutdown()
    quit()

In [ ]:
# total de ativos
mt5.symbols_total()

In [ ]:
# quais ativos temos -> infos complexas
mt5.symbols_get()

In [ ]:
# infos de ativos especificos
mt5.symbol_info("IBOV11")._asdict()

In [ ]:
# valor atual do ativo
mt5.symbol_info_tick("IBOV11")

### Estrutura para criar o dataframe de OHLC
##### OHLC -> open/high/low/close
```
copy_rates_range(
   symbol,       // nome do ativo
   timeframe,    // timeframe -> pesquisar sobre timeframes dentro do MT5
   date_from,    // data inicial
   date_to       // data final
   )
```

<table>
<tr><th>Janelas de Tempo </th><th>Valores Específicos</th></tr>
<tr><td>

|Timeframes   |Descrição   |
|---|---|
|TIMEFRAME_M1   | 1 minuto  |
|TIMEFRAME_M2   | 2 minutos  |
|TIMEFRAME_M3   | 3 minutos  |
|TIMEFRAME_M4   | 4 minutos  |
|TIMEFRAME_M5   | 5 minutos  |
|TIMEFRAME_M6   | 6 minutos  |
|TIMEFRAME_M10   | 10 minutos  |
|TIMEFRAME_M12   | 12 minutos  |
|TIMEFRAME_M15   | 15 minutos  |
|TIMEFRAME_M20   | 20 minutos  |
|TIMEFRAME_M30   | 30 minutos  |
|TIMEFRAME_H1   | 1 hora  |
|TIMEFRAME_H2   | 2 horas  |
|TIMEFRAME_H3   | 3 horas  |
|TIMEFRAME_H4   | 4 horas  |
|TIMEFRAME_H6   | 6 horas  |
|TIMEFRAME_H8   | 8 horas  |
|TIMEFRAME_H12   | 12 horas  |
|TIMEFRAME_D1   | 1 dia  |
|TIMEFRAME_W1   | 1 semana  |
|TIMEFRAME_MN1   | 1 mês  |

</td><td>
    
|ID   |Descrição   |
|---|---|
|MODE_OPEN   |Preço de abertura |
|MODE_LOW   |Preço mínimo   |
|MODE_HIGH   |Preço máximo   |
| MODE_CLOSE  |Preço de fechamento   |
|MODE_VOLUME   |Volume de ticks   |
|MODE_REAL_VOLUME   |Volume real   |
|MODE_SPREAD   |Spread   |
    
</td></tr> </table>

In [20]:
import pandas as pd
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go

In [23]:
# array que sera usado em um df posteriormente
data = mt5.copy_rates_range("PETR3", mt5.TIMEFRAME_W1,  #daily
                                            datetime(2022, 1, 1),
                                            datetime.now())

In [24]:
df = pd.DataFrame(data)
df

          time   open   high    low  close  tick_volume  spread  real_volume
0   1641081600  21.37  22.30  21.10  21.36       184779       1    109550400
1   1641686400  21.27  24.07  21.06  23.95       222209       1    134284400
2   1642291200  23.85  24.35  23.43  23.97       157436       1     76147400
3   1642896000  23.87  26.19  23.12  24.87       204990       1    120136300
4   1643500800  24.98  25.37  24.03  24.88       196422       1     95429100
5   1644105600  24.85  25.82  23.85  25.77       180438       1     87096600
6   1644710400  25.77  25.91  24.21  24.85       154282       1     70452600
7   1645315200  24.86  26.09  24.21  25.20       191899       1     91241700
8   1645920000  26.31  26.38  25.14  25.62       101327       1     49751100
9   1646524800  25.91  25.98  23.24  24.12       241060       1    138902800
10  1647129600  24.12  24.35  22.17  22.98       197901       1    127713200
11  1647734400  23.02  24.47  22.98  24.25       149477       1     68031100
12  1648339200  24.08  24.79  23.31  24.41       151166       1     81385800
13  1648944000  24.23  25.81  23.81  25.70       136336       1     71915700
14  1649548800  25.43  26.41  25.20  26.11       147669       1     76437600
15  1650153600  25.91  26.43  24.95  25.07        99769       1     61409100
16  1650758400  24.73  26.30  24.36  25.13       122811       1     58003400
17  1651363200  25.17  26.97  24.16  26.82       176716       1     89741600
18  1651968000  26.55  27.94  25.64  27.52       185600       1    116101600
19  1652572800  27.61  28.58  27.40  28.31       152119       1     80259400
20  1653177600  28.51  29.51  27.89  27.97       174500       1     86957600
21  1653782400  28.18  28.18  26.57  27.98       128029       1     71365600
22  1654387200  28.09  28.70  26.82  27.28       103656       1     53386400
23  1654992000  26.89  27.59  23.91  24.81       147702       1     93166200
24  1655596800  23.86  25.51  23.68  23.96       131915       1     77674400
25  1656201600  24.20  26.44  24.20  25.79       146101       1     74345700
26  1656806400  25.83  26.63  24.27  25.86       109907       1     50200800
27  1657411200  25.51  25.94  24.51  25.12        88684       1     45582800
28  1658016000  25.46  26.62  25.36  26.47       106714       1     69946200
29  1658620800  26.98  30.98  26.81  30.64       171963       1    105211100
30  1659225600  30.62  31.25  29.72  31.10       152658       1     74870000
31  1659830400  31.18  34.90  31.18  34.88       215963       1    141639300
32  1660435200  33.89  37.23  33.42  35.31       168521       1     97770100
33  1661040000  35.07  38.30  34.16  37.46       153164       1     86811300
34  1661644800  37.62  38.76  35.44  37.29       149914       1    127384500
35  1662249600  37.80  37.96  35.21  35.48        98345       1     64035200
36  1662854400  35.90  36.50  34.00  34.41       152702       1     96658300
37  1663459200  33.90  35.56  32.74  32.90       171142       1    138041200
38  1664064000  32.80  33.70  31.89  33.08       169383       1    116749900
39  1664668800  35.36  38.41  35.15  37.44       251643       1    137987500
40  1665273600  37.60  38.52  36.09  37.15       114596       1     76761600
41  1665878400  37.14  39.28  36.46  39.18        64266       1     63506000

In [ ]:
data2 = mt5.copy_rates_range("BOVA11", mt5.TIMEFRAME_W1,  #weekly
                                            datetime(2015, 1, 1),
                                            datetime.now())
print("Semanal: ", len(data2), "\n", "Diario: ", len(data))

In [ ]:
ohlc_df = pd.DataFrame(data)
# ohlc_df['time'] = ohlc_df['time'].apply(lambda x: datetime.fromtimestamp(x).strftime("%B %d, %Y %I:%M")) # seria interessante ter os minutos e horas se o timeframe fosse semelhante
ohlc_df['time']=pd.to_datetime(ohlc_df['time'], unit='s')
ohlc_df

#### O que é um TIMEFRAME?
Um timeframe indica o delta de tempo que uma vela se refere. Quanto maior o timeframe estabelecido escolhido, maior o intervalo que cada vela representa

In [ ]:
# ohlc -> open/high/low/close
# grafico simples para ver os preços de fechamento no tempo

fig = px.line(ohlc_df, x=ohlc_df['time'], y=ohlc_df['close'])
fig.update_xaxes(dtick="M8", tickformat="%b/%Y")
fig.show()

In [ ]:
# Naked price action -> raw data
fig = go.Figure(data=[go.Candlestick(x=ohlc_df['time'],
                open=ohlc_df['open'],
                high=ohlc_df['high'],
                low=ohlc_df['low'],
                close=ohlc_df['close'])])
fig.update_xaxes(dtick="M8", tickformat="%b/%Y")
fig.show()

### About Candlestick Graphs
##### Green - Significa que o preço subiu naquele timeframe arbitrário
- Closing Price 
- Real Body
- Opening Price

##### Red - Significa que o preço caiu naquele timeframe arbitrário
- Opening Price
- Real Body
- Closing Price

##### Shadows, Tails or Wicks - Linhas que saem do Real Body
- Representam o maior e menor preço naquele período de tempo
- Shadows -> Upper shadow or Lower Shadow
- Wick -> Pavio, Upper Shadow
- Tail -> Calda, Lower Shadow

##### O que representa o tamanho do Real Body?
- Basicamente a expectativa do mercado
- Interpretar o swing da vela e não somente o output (se positivo ou negativo)
- Notar os Tails, são informações valiosas sobre como ocorreu
- Exemplo: Bearish Candle com pequeno Real Body e grande Tail (bottom shadow)
    - Significa que naquele dia o preço caiu bastante, por mais que seja uma Bearish Candle, o mercado tende a subir
    - O Real Body é pequeno
    - A Tail é grande
    - Representa um comeback

##### Doji Candles - Indecision Candles
- São velas onde o preço não variou no tempo ou variou de maneira inexpressiva

#### Tick Data
##### Possível ver o spread, os bids e os asks

In [13]:
data_tick = mt5.copy_ticks_range("BOVA11",
                                 datetime(2020, 1, 1),
                                 datetime.now(),
                                 mt5.COPY_TICKS_ALL)

numpy.ndarray

In [14]:
data_tick = data_tick[:90000]

In [15]:
tick_df = pd.DataFrame(data_tick)
#tick_df['time'] = tick_df['time'].apply(lambda x: datetime.fromtimestamp(x).strftime("%x"))
#tick_df['time'] =  pd.to_datetime(tick_df['time'])

tick_df

,time,bid,ask,last,volume,time_msc,flags,volume_real
0,1632735000,108.52,109.10,0.00,0,1632735000665,6,0.0
1,1632735900,109.10,108.30,0.00,0,1632735900477,6,0.0
2,1632735902,109.10,108.00,0.00,0,1632735902638,4,0.0
3,1632735903,113.00,108.00,0.00,0,1632735903345,2,0.0
4,1632735904,113.00,92.68,0.00,0,1632735904335,4,0.0
...,...,...,...,...,...,...,...,...
89995,1632835102,107.09,107.10,107.10,10,1632835102373,312,10.0
89996,1632835102,107.09,107.10,107.09,10,1632835102711,344,10.0
89997,1632835102,107.09,107.10,107.09,5,1632835102716,344,5.0
89998,1632835102,107.09,107.10,107.09,327,1632835102906,344,327.0
89999,1632835102,107.09,107.10,107.09,300,1632835102915,344,300.0

In [ ]:
ticks = mt5.copy_ticks_range(
    'PETR3', 
    datetime(2021, 1, 1), 
    datetime(2021, 1, 7), 
    mt5.COPY_TICKS_TRADE
    )
ticks_df = pd.DataFrame(ticks)
ticks_df